# Load Data

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
train=pd.read_csv('/content/drive/MyDrive/Data Science Project - Team D/data/raw-data/train.csv')

train.describe().apply(lambda s: s.apply('{0:.5f}'.format))

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
count,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,...,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000
mean,0.10049,10.67991,-1.62762,10.71519,6.79653,11.07833,-5.06532,5.40895,16.54585,0.28416,...,3.23444,7.43841,1.92784,3.33177,17.99378,-0.14209,2.30334,8.90816,15.87072,-3.32654
std,0.30065,3.04005,4.05004,2.64089,2.04332,1.62315,7.86327,0.86661,3.41808,3.33263,...,4.55992,3.02327,1.47842,3.99203,3.13516,1.42937,5.45437,0.92163,3.01095,10.43802
min,0.00000,0.40840,-15.04340,2.11710,-0.04020,5.07480,-32.56260,2.34730,5.34970,-10.50550,...,-14.09330,-2.69170,-3.81450,-11.78340,8.69440,-5.26100,-14.20960,5.96060,6.29930,-38.85280
25%,0.00000,8.45385,-4.74003,8.72247,5.25408,9.88318,-11.20035,4.76770,13.94380,-2.31780,...,-0.05883,5.15740,0.88977,0.58460,15.62980,-1.17070,-1.94693,8.25280,13.82970,-11.20847
50%,0.00000,10.52475,-1.60805,10.58000,6.82500,11.10825,-4.83315,5.38510,16.45680,0.39370,...,3.20360,7.34775,1.90130,3.39635,17.95795,-0.17270,2.40890,8.88820,15.93405,-2.81955
75%,0.00000,12.75820,1.35862,12.51670,8.32410,12.26112,0.92480,6.00300,19.10290,2.93790,...,6.40620,9.51253,2.94950,6.20580,20.39653,0.82960,6.55673,9.59330,18.06472,4.83680
max,1.00000,20.31500,10.37680,19.35300,13.18830,16.67140,17.25160,8.44770,27.69180,10.15130,...,18.44090,16.71650,8.40240,18.28180,27.92880,4.27290,18.32150,12.00040,26.07910,28.50070

In [3]:
test=pd.read_csv('/content/drive/MyDrive/Data Science Project - Team D/data/raw-data/test.csv')
test.describe().apply(lambda s: s.apply('{0:.5f}'.format))

,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
count,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,...,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000,200000.00000
mean,10.65874,-1.62424,10.70745,6.78821,11.07640,-5.05056,5.41516,16.52914,0.27713,7.56941,...,3.18977,7.45827,1.92594,3.32202,17.99697,-0.13366,2.29090,8.91243,15.86918,-3.24634
std,3.03672,4.04051,2.63389,2.05272,1.61646,7.86929,0.86469,3.42448,3.33337,1.23187,...,4.55124,3.02519,1.47997,3.99560,3.14065,1.42968,5.44635,0.92090,3.00872,10.39859
min,0.18870,-15.04340,2.35520,-0.02240,5.48440,-27.76700,2.21640,5.71370,-9.95600,4.24330,...,-14.09330,-2.40700,-3.34090,-11.41310,9.38280,-4.91190,-13.94420,6.16960,6.58400,-39.45780
25%,8.44298,-4.70012,8.73560,5.23050,9.89108,-11.20140,4.77260,13.93390,-2.30390,6.62380,...,-0.09500,5.16650,0.88298,0.58760,15.63478,-1.16070,-1.94860,8.26008,13.84727,-11.12400
50%,10.51380,-1.59050,10.56070,6.82235,11.09975,-4.83410,5.39160,16.42270,0.37200,7.63200,...,3.16240,7.37900,1.89260,3.42850,17.97760,-0.16200,2.40360,8.89280,15.94340,-2.72595
75%,12.73960,1.34340,12.49503,8.32760,12.25340,0.94257,6.00580,19.09455,2.93003,8.58482,...,6.33648,9.53110,2.95600,6.17420,20.39173,0.83790,6.51980,9.59590,18.04520,4.93540
max,22.32340,9.38510,18.71410,13.14200,16.03710,17.25370,8.30250,28.29280,9.66550,11.00360,...,20.35900,16.71650,8.00500,17.63260,27.94780,4.54540,15.92070,12.27580,26.53840,27.90740

# Prepare Data

In [ ]:
from tqdm import tqdm

col_names = [f"var_{i}" for i in range(200)]
for col in tqdm(col_names):
    count = test[col].value_counts()
    uniques = count.index[count == 1]
    test[col + "_u"] = test[col].isin(uniques)

test["unique"] = test[[col + "_u" for col in col_names]].any(axis=1)
test["unique"].sum()


real_test = test.loc[test["unique"], ["ID_code"] + col_names]
fake_test = test.loc[~test["unique"], ["ID_code"] + col_names]
train_and_test = pd.concat([train, real_test], axis=0)

for col in tqdm(col_names):
    count = train_and_test[col].value_counts().to_dict()
    train_and_test[col+"_unique"] = train_and_test[col].apply(
        lambda x: 1 if count[x] == 1 else 0).values
    fake_test[col+"_unique"] = 0 


real_test = train_and_test[train_and_test["ID_code"].str.contains("test")].copy()
real_test.drop(["target"], axis=1, inplace=True)
train = train_and_test[train_and_test["ID_code"].str.contains("train")].copy()
test = pd.concat([real_test, fake_test], axis=0)

# Split and normalize data

In [4]:
#shuffle data
#train = train.sample(frac=1)

X = train.drop(['target', 'ID_code'], axis=1)
y=train[['target']]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
X = scaler.fit_transform(X) 

from sklearn.model_selection import train_test_split
# split into 90% train, 10% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)

# Lazy predict

In [5]:
import lazypredict
from lazypredict.Supervised import LazyClassifier

In [ ]:
clf = LazyClassifier(verbose=0,ignore_warnings=True, custom_metric=None)
models,predictions = clf.fit(X_train, X_test, y_train, y_test)
print(models)

 17%|█▋        | 5/29 [45:56<2:46:30, 416.27s/it]